### PR TITLE
increase sql table owner_public_key from varchar(256) to 512

### LINKED ISSUE #178: increase sql table owner_public_key from varchar(256) to 512
The MIRACL public key format has 258 characters  (example: 0420ec9dd58f2d16babe5eddd0990472ef7f05fd707e3a4171e61ba9360fe4a3891d9bcf8a86b0b270d104c1a2a093f744d27793927910b38be9883ec0b06ca3490569516d05cfdfb66f64ac13681905ec639930dc66ae889944d4a0e3fbf249fc0d52adb860e55487251acbd90e8f1b5563e71e67af1e110ce986ff41df34a7ed)

very sadly, this 258 string is just 2 character more than the 256 limit.

The error message I'm seeing is:

`{"code":"invalid_parameters","error":"invalid_parameters: Invalid allocation id passed.verify_allocation: verifying allocation transaction error: ERROR: value too long for type character varying(256) (SQLSTATE 22001)"}`

It can be replicated with this curl call (although the six network is currently down unfortunately)
```
curl 'http://six.devnet-0chain.net:31301/v1/file/upload/d2f7e87dcd5dce7431112310ca811435925a40f1758c51cc7d3d9a93bfd3cdf1' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'x-app-client-id: 69c4e00f68457c76a473e71368effd6542853c61d27f9bb1136bc131d96b428d' \
  -H 'x-app-client-key: 0420ec9dd58f2d16babe5eddd0990472ef7f05fd707e3a4171e61ba9360fe4a3891d9bcf8a86b0b270d104c1a2a093f744d27793927910b38be9883ec0b06ca3490569516d05cfdfb66f64ac13681905ec639930dc66ae889944d4a0e3fbf249fc0d52adb860e55487251acbd90e8f1b5563e71e67af1e110ce986ff41df34a7ed' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36' \
  -H 'content-type: multipart/form-data; boundary=6834d1dc50f4e20a1997f3342a4495650798577a0421bb1ace2877d26c67' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:82' \
  -H 'Referer: http://localhost:82/' \
  -H 'Accept-Language: en-US,en;q=0.9' \
  --data-raw $'--6834d1dc50f4e20a1997f3342a4495650798577a0421bb1ace2877d26c67\r\nContent-Disposition: form-data; name="uploadFile"; filename="demo.txt"\r\nContent-Type: application/octet-stream\r\n\r\n./dem\r\n--6834d1dc50f4e20a1997f3342a4495650798577a0421bb1ace2877d26c67\r\nContent-Disposition: form-data; name="connection_id"\r\n\r\n3803579151\r\n--6834d1dc50f4e20a1997f3342a4495650798577a0421bb1ace2877d26c67\r\nContent-Disposition: form-data; name="uploadMeta"\r\n\r\n{"connection_id":"3803579151","filename":"demo.txt","filepath":"/demo.txt","content_hash":"09530638b98cad900ea1d2c46e528acdbbf6d2ac","merkle_root":"4c8d8c83778e3e74a66ce6461c247d576d8bf91848f87733cc3c8f6189790298","actual_hash":"3d62f33e26cb3479e3cba50a4eda8266aa98aa74","actual_size":10,"actual_thumb_size":0,"actual_thumb_hash":"","mimetype":"application/octet-stream","attributes":{}}\r\n--6834d1dc50f4e20a1997f3342a4495650798577a0421bb1ace2877d26c67--\r\n' \
  --compressed \
  --insecure -i
```

### PR DESCRIPTION
**Pull request by mallochine**
to fix #178

### CODE REVIEW

File: sql/01-create-table.sql [hunk 1]
```diff
@@ -14,7 +14,7 @@ CREATE TABLE allocations(
     size BIGINT NOT NULL DEFAULT 0,
     used_size BIGINT NOT NULL DEFAULT 0,
     owner_id VARCHAR(64) NOT NULL,
-    owner_public_key VARCHAR(256) NOT NULL,
+    owner_public_key VARCHAR(512) NOT NULL,
```
Comment (shravanshetty1) [inline sql/01-create-table.sql:17]: This change should probably be an alter statement in a new file. I think we need to document how we handle database changes, currently on the info i am operating on there doesnt seem to be a way to protect against breaking changes.

**Review by shravanshetty1 — CHANGES_REQUESTED** [review]

File: sql/01-create-table.sql (hunk 1 above)
Comment (mallochine) [reply sql/01-create-table.sql:17]: is that in a new sql file? Is this something you could submit since I'm not clear on how the sql/ directory here should be structured.

whatever gets the varchar limit to be 512 in the end, I'll be happy with it.

Comment (shravanshetty1) [reply sql/01-create-table.sql:17]: You will have to add a new sql file just like all the others

Comment (mallochine) [reply sql/01-create-table.sql]: OK please check the new files now.

File: sql/14-increase_owner_pubkey.sql [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+-- Increase the char limit of owner_public_key from 256 to 512.
+--
+
+-- pew-pew
+\connect blobber_meta;
+
+-- in a transaction
+BEGIN;
+    ALTER TABLE allocations
+        MODIFY COLUMN owner_public_key varchar(512) NOT NULL;
```
Comment (shravanshetty1) [inline sql/14-increase_owner_pubkey.sql:11]:
```
postgres-post_1  | /blobber/bin/postgres-entrypoint.sh: running /blobber/sql/14-increase_owner_pubkey.sql
postgres-post_1  | You are now connected to database "blobber_meta" as user "postgres".
postgres-post_1  | BEGIN
postgres_1       | 2021-06-01 13:17:32.305 UTC [108] ERROR:  syntax error at or near "MODIFY" at character 33
postgres_1       | 2021-06-01 13:17:32.305 UTC [108] STATEMENT:  ALTER TABLE allocations
postgres_1       |              MODIFY COLUMN owner_public_key varchar(512) NOT NULL;
postgres-post_1  | psql:/blobber/sql/14-increase_owner_pubkey.sql:11: ERROR:  syntax error at or near "MODIFY"
postgres-post_1  | LINE 2:         MODIFY COLUMN owner_public_key varchar(512) NOT NULL...
postgres-post_1  |                 ^
postgres-post_1  | ROLLBACK
postgres-post_1  | 
postgres-post_1  | 
blobber1_postgres-post_1 exited with code 0
```

**Review by shravanshetty1 — CHANGES_REQUESTED** [review]

File: sql/14-increase_owner_pubkey.sql [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+-- Increase the char limit of owner_public_key from 256 to 512.
+--
+
+-- pew-pew
+\connect blobber_meta;
+
+-- in a transaction
+BEGIN;
+    ALTER TABLE allocations
+        ALTER COLUMN owner_public_key varchar(512) NOT NULL;
```
Comment (shravanshetty1) [inline sql/14-increase_owner_pubkey.sql:11]:
```
postgres-post_1  | 
postgres-post_1  | /blobber/bin/postgres-entrypoint.sh: running /blobber/sql/14-increase_owner_pubkey.sql
postgres-post_1  | You are now connected to database "blobber_meta" as user "postgres".
postgres-post_1  | BEGIN
postgres-post_1  | psql:/blobber/sql/14-increase_owner_pubkey.sql:11: ERROR:  syntax error at or near "varchar"
postgres-post_1  | LINE 2:         ALTER COLUMN owner_public_key varchar(512) NOT NULL;
postgres-post_1  |                                               ^
postgres-post_1  | ROLLBACK
postgres-post_1  | 
postgres-post_1  | 
blobber1_postgres-post_1 exited with code 0

```

**Review by shravanshetty1 — CHANGES_REQUESTED** [review]

File: sql/14-increase_owner_pubkey.sql (hunk 3 above)
Comment (mallochine) [reply sql/14-increase_owner_pubkey.sql]: OK I pushed a fix that should fix it for postgres 9.1 and above

**Review by andrenerd — APPROVED** [review]

**Comment by mallochine** [comment]
@andrenerd did you get to test the SQL change in the same way shravan did? I already submitted 3 other commits that all had SQL syntax errors so I'm worried.

File: sql/14-increase_owner_pubkey.sql [hunk 4]
```diff
@@ -8,5 +8,5 @@
 -- in a transaction
 BEGIN;
     ALTER TABLE allocations
-        ALTER COLUMN owner_public_key varchar(512) NOT NULL;
+        ALTER COLUMN owner_public_key TYPE varchar(512) NOT NULL;
```
Comment (shravanshetty1) [inline sql/14-increase_owner_pubkey.sql:11]:
```
postgres-post_1  | /blobber/bin/postgres-entrypoint.sh: running /blobber/sql/14-increase_owner_pubkey.sql
postgres-post_1  | You are now connected to database "blobber_meta" as user "postgres".
postgres-post_1  | BEGIN
postgres-post_1  | psql:/blobber/sql/14-increase_owner_pubkey.sql:11: ERROR:  syntax error at or near "NOT"
postgres-post_1  | LINE 2: ...   ALTER COLUMN owner_public_key TYPE varchar(512) NOT NULL;
postgres-post_1  |                                                               ^
postgres_1       | 2021-06-01 15:25:01.695 UTC [107] ERROR:  syntax error at or near "NOT" at character 81
postgres_1       | 2021-06-01 15:25:01.695 UTC [107] STATEMENT:  ALTER TABLE allocations
postgres_1       |              ALTER COLUMN owner_public_key TYPE varchar(512) NOT NULL;
postgres-post_1  | ROLLBACK
postgres-post_1  | 
postgres-post_1  | 
blobber1_postgres-post_1 exited with code 0
```

**Review by shravanshetty1 — CHANGES_REQUESTED** [review]

File: sql/14-increase_owner_pubkey.sql (hunk 4 above)
Comment (mallochine) [reply sql/14-increase_owner_pubkey.sql]: looks like NOT NULL is not needed, since that contraint is not changed by Postgres.

**Review by shravanshetty1 — APPROVED** [review]
